# Generated by Django 5.1 on 2024-08-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('tipe', models.CharField(choices=[('Membership', 'Membership'), ('Trainer', 'Trainer')], max_length=10)),
                ('durasi_hari', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
