# Generated by Django 5.1 on 2024-08-29 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainersession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.produk'),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='trainer_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trainer.trainersession'),
        ),
    ]
