# Generated by Django 5.1 on 2024-08-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=7)),
                ('kategori', models.CharField(choices=[('Denda', 'Denda'), ('Trainer', 'Trainer'), ('Membership', 'Membership'), ('Operasional', 'Operasional')], max_length=15)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('Berhasil', 'Berhasil'), ('Batal', 'Batal'), ('Belum Bayar', 'Belum Bayar')], default='Belum Bayar', max_length=15)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
